### ISSUE TITLE
Sentinel connection strategies

### ISSUE THREAD

**Issue by ryan-shaw** [redis/redis-py#1179]
I thought it would be good to have an issue to track this as I see 2 PRs that are relatively old, #654 and #770 

We ran into this issue today, we have 3 sentinel instances that we were changing hosts on, these are across 3 AZs, 1a, 1b, and 1c. All our configs list the sentinel starting with 1a.

We started with the upgrade to 1c which involved shutting down the host and moving IP address, all fine and 0 impact. When we got to 1a the sentinel was shutdown and everything worked fine with no latency change, but when the host was shutdown we had a large latency spike to around 1s and only now found out it's because the sentinels list always uses the first server. When the host was shutdown the connect timeouts started to be hit (we set them at 1.2s). 

It would be nice to see different strategy options so behaviour can be more predictable across all sentinels.

**Comment by BingerCoder** [comment]
I push new commit, user can set weight of each instance

**Comment by RoeyPrat** [comment]
sorry for the long post 😄 
### existing implementation:
looking at [discover_master](https://github.com/andymccurdy/redis-py/blob/e06af2a0f648d4241930479884533bc53cc9fdfb/redis/sentinel.py#L200), the current expected behavior is that `Sentinel` instance has a list of sentinel hosts, and will cycle through them until one of them returns a successful response.
Importantly, once a successful response is returned, `Sentinel` instance will "promote" the good sentinel host to be the first in the list - meaning next time the first sentinel will succeed.
This means in case of X out of Y sentinels are down, we will see at most X timeouts per instance, and then no more timeouts until the next sentinel goes down.
The symptoms you speak of seem to be expected, as we see one timeout per sentinel instance, and then back to normal.
Lowering the connect timeout might help with the symptom, but I bet you thought of that.

### alternate strategy 1 - shuffle at init:
With this strategy, we shuffle once during `Sentinel` instance initialization. 
This is the strategy in PR https://github.com/andymccurdy/redis-py/pull/654 commit dc7dd8a, though it is referred to in the PR as "Round-robin".
After the initial shuffle, the `Sentinel` instance will still "stick" to the first sentinel in the list, until it fails.
This might be advantageous to some users - if you have many `Sentinel` instances in one of more clients, and you do a rolling update in the sentinels. each time a sentinel goes down, statistically, only some of the `Sentinel` instances will fail, since they have different orders of the list. 
Another benefit is that the first master in the list is not "hammered" by all the instances - the traffic is somewhat .
The downside is that we lose the expected behavior of the instance simply going down the provided list - this forces randomness on all users.
We can add this add an optional flag in initialization, but the user can do it themselves just as easy:
```python
sentinel = Sentinel(random.shuffle([(sentinel_host_1, port),(sentinel_host_2, port)]))
```
**If this `shuffle at init` option is of interest, I suggest adding it to the documentation, not to the code.**

### alternate strategy 2 - weighted random:
With this strategy, we shuffle every time we `discover_master` and do not change the list order if a specific host succeeds.
This is seen in PR https://github.com/andymccurdy/redis-py/pull/770, commit 1dbd365.
This is nice as you get predictable load balancing between the sentinels. I wonder why weights are necessary - perhaps if one sentinel is more predictable or just bigger, but I'm not sure how common that is. 
The issue I have with this approach is that we lose the "stickiness". If for example sentinel x gets 33% of the traffic, and it's in maintenance, 33% of the requests will time out. unlike the current implementation, the order of hosts in the list doesn't matter, so if one of the sentinels is down for a long time, this will continue to affect latency.

I think a better approach is to keep the stickiness, but add randomness to the choice if the first host fails.
Another option is to have random weights that are updated if a host answers, and updated if a host does not answer, but this is relatively complex.

@ryan-shaw @BingerCoder @andymccurdy What are your thoughts on these options? did I miss something?

**Comment by BingerCoder** [comment]
You are right~ the strategy 1 is useful~ I see

**Comment by Frank5000** [comment]
@RoeyPrat could weights be adjusted on successful connections? In your example sentinel x's portion of the traffic would gradually shrink as the other 2 instances' weights increase/sentinel x's weight decreases. We can set a floor to ensure that when sentinel x comes back up its score will recover, or simply reset the weights at some interval.
