### ISSUE TITLE
PyPI doesn't have recent Redis changes

### ISSUE THREAD

**Issue by dsoprea** [redis/redis-py#1428]
As mentioned, here:

https://github.com/andymccurdy/redis-py/pull/1393#issuecomment-739149591

...The fixes to the modules-list in the INFO response was pushed to the repository three months ago but has not yet been pushed to PyPI.

I asked a week ago. It seems like a trivial thing to do and I'm not clear why I couldn't even get an acknowledgement. Since that's a closed issue, I didn't want this to fall off the radar.

**Comment by dsoprea** [comment]
Bump. Come on, guys. You've fixed the bug. Now just push the changes. It's been months.

**Comment by dsoprea** [comment]
Bump.

**Comment by andymccurdy** [comment]
Unfortunately the 4.x branch with backwards incompatible changes got merged into master, so the next release of redis-py needs to be 4.0. There's still some effort that needs to happen to complete 4.0, and I don't have time to do that right now.

**Comment by hithwen** [comment]
Any updates on this?

**Comment by sirosen** [comment]
I understand that this isn't ready to release, and it's often really hard to juggle FOSS work with other things. But it's hard for anyone in the community to see what's going on or how to help out right now.

I've been hesitant to use redis-py in at least one production application because the maintenance status wasn't clear to me at the time.

Can we either retitle and pin this issue or make and pin a replacement issue, "Release 4.0"?

---

Another thought: if people are installing from the 4.0 branch, that's bad. Can a 4.0.0a1 release go out to remove the temptation (especially for less experienced teams, who may not realize what a branch install really means)?

**Comment by chayim** [comment]
First off, thank you for your patience, and the question. I just pushed [4.0.0b1 to Pypi](https://pypi.org/project/redis/4.0.0b1/) this morning! I'm going to close this off accordingly - as you're bang on, we're going to go through a series of betas, etc.
