### ISSUE TITLE
expireat with timezone

### ISSUE THREAD

**Issue by MrScallion** [redis/redis-py#1463]
**Version**: 3.5.3

**Platform**: Windows 10 Python 3.7.9

I got timezone problem, then I checked the source code there has no code to deal timezone problem
![image](https://user-images.githubusercontent.com/43311996/112412910-3e7ec300-8d5a-11eb-8dc8-6b68edfb1258.png)

_Originally posted by @MrScallion in https://github.com/andymccurdy/redis-py/issues/598#issuecomment-806329988_

**Comment by chayim** [comment]
The Redis [EXPIREAT](https://redis.io/commands/EXPIREAT) command is based on a unix timestamp, while the redis-py implementation allows one to define either an int (pure unix time) or a python timestamp.

The datetime library, combined with pytz becomes timezone aware, as opposed to this being a function of redis-py. See [this StackOverflow](https://stackoverflow.com/questions/7065164/how-to-make-a-timezone-aware-datetime-object-in-python), or the modified version of the code below - purely so that one can see the valid types:


```
import datetime
import pytz

unaware = datetime.datetime(2011, 8, 15, 8, 15, 12, 0)
aware = datetime.datetime(2011, 8, 15, 8, 15, 12, 0, pytz.UTC)

now_aware = pytz.utc.localize(unaware)
print(isinstance(now_aware, datetime.datetime))
```
