### ISSUE TITLE
Request to add serialization and deserialization functions

### ISSUE THREAD

**Issue by whichdew** [redis/redis-py#1479]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

It is very strange why redis does not directly add serialization and deserialization steps when it is implemented, but later I thought that it should take into account the problem of multiple clients.
Because if redis uses pickle to serialize data by default, the content seen in clients such as redis-cli will be garbled, so the serialization process should be completed when the user calls it. 
However, having said that, I still want redis itself to have these hook functions, so that users will not have to repeat the steps. For example, we can finally pass in the parameter when initializing redis: Redis(serializer=pickle), no need to serialize the key, and can be set to serialize only when the value is irregular type

**Comment by andymccurdy** [comment]
Automatic serialization and deserialization isn't practical. While you *could* add a hook to `get()` to deserialize and `set()` to serialize, what happens when you also want to get the value of a key that you have incremented via `incrby()`. What happens when you push values on to or pop values off of a list? Are those values also serialized and deserialized? There are many more examples.

I believe it's better for the user to control what they're serializing and deserializing explicitly.

**Comment by xdandyx** [comment]
> Automatic serialization and deserialization isn't practical. While you _could_ add a hook to `get()` to deserialize and `set()` to serialize, what happens when you also want to get the value of a key that you have incremented via `incrby()`. What happens when you push values on to or pop values off of a list? Are those values also serialized and deserialized? There are many more examples.
> 
> I believe it's better for the user to control what they're serializing and deserializing explicitly.

I agree with what you said above. However, when providing built-in serialization support, it saves users a lot of trouble, but it will bring you more workload. The problem you mentioned above can be attributed to whether the data types are uniform. However, when providing serialization support, it is the user's business to ensure that the data are uniform. For example, when a user operates a database with `Redis (serializer = pickle)`, he needs to ensure that the existing data is serialized in the same way. Otherwise, he should consider not using serialization or switching the appropriate serialization method at runtime.
In order to make this module compatible with the previous design after the introduction of serialization function, I think it can be designed as follows:
1. The basic types supported by redis need not be serialized
2. Under the condition of 1, redis calls the serialization function when writing
3. Under the condition of 1, when reading redis, first try to deserialize, if it fails, call the user's onerror callback function
