### ISSUE TITLE
pexpire api inconsistency

### ISSUE THREAD

**Issue by WisdomPill** [redis/redis-py#1664]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on? potentially all

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure) potentially all 

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

`expire` and `pexpire` behave differently like many commands that return 0 or 1, the response is parsed into a boolean.

In the case of `expire` it is parsed as boolean, while with `pexpire` not, even if they are basically doing the same.

Thanks to @puittenbroek who discovered the issue in https://github.com/jazzband/django-redis/pull/565#discussion_r740043060

It is a very quick fix, I would love to start contributing fixing it.

**Comment by chayim** [comment]
@WisdomPill As always, thanks a tonne for reporting this - including the helpful link to the django-redis issue. 

Uhoh, be careful what you wish for! Seriously though, I assigned it to you, since you asked ;). redis/client.py would use the changes in the RESPONSE_CALLBACKS. Those two commands don't currently have int mappings.

I'm hip deep in tests and other things. But - if you think it'll take more than a week, I'm happy to grab it back from you. Otherwise, frankly, I love sharing the load. Bring it!!!
