### ISSUE TITLE
Objection to integration with nonfree Redis modules

### ISSUE THREAD

**Issue by ddevault** [redis/redis-py#1715]
redis-py 4.0.0 introduced integrations with the non-free Redis modules for search, timeseries, and JSON. I am filing a ticket to object to this integration. Such features should be supported via a separate module, or modules.

One problem this causes is the inability to run the test suite without depending on non-free Redis modules. A company which wants to verify the redis-py test suite, but cannot comply with the Redis source available license, cannot verify their installation of redis-py is working correctly.

I work on the Alpine Linux package for redis-py and I have prepared a downstream patch which removes these integrations from redis-py, as we are unable to verify the package with these modules present.

**Comment by ddevault** [comment]
Bump. It seems the latest version shipped without addressing this issue.

**Comment by ddevault** [comment]
Another release has shipped without addressing this issue.

Explicitly Cc'ing those who were credited in the release for comment:

@Andrew-Chen-Wang, @AvitalFineRedis, @Enchufa2, @barshaul, @chayim, @dvora-h, @jdieter, @salty-horse, @sbv-csis and @tony

**Comment by Andrew-Chen-Wang** [comment]
Next time, please ping the head maintainer of any open source repository concerning a pressing issue and respect people's time since this fills up our inboxes, too. Some of these people are not maintainers at all.

In regards to this issue, I agree. I would suggest you make a PR that adds a new tox section that excludes the redismod marker. Does that work? Again, if so, please file a PR. The paid mods are RediSearch, RedisJSON, RedisGraph, RedisTimeSeries, and RedisBloom, all of which are here.

RedisAI will soon be added (https://github.com/redis/redis-py/pull/1830), but they did not include the pytest marker for redismod as it is free. So the PR for a new tox testenv section should be simple.

Thanks,
Andrew

**Comment by ddevault** [comment]
The tests are just one of many problems with incorporating nonfree modules into this project. They should be distributed as separate modules in PyPI.

**Comment by ddevault** [comment]
It's not clear who the "head maintainer" of this project is, by the way. "RedisLabs" is vague.

**Comment by ddevault** [comment]
I will no longer be updating the py3-redis package on Alpine Linux pending a resolution on this issue.

**Comment by Andrew-Chen-Wang** [comment]
> The tests are just one of many problems with incorporating nonfree modules into this project. They should be distributed as separate modules in PyPI.

I think the decision to split has passed the moment it was merged with redis-py. If these module packages were archived by the maintainers, it means the maintainers didn't want to maintain. Or at least a history of paused maintainership is known. Kind of like how I don't have time to look after aioredis; neither do the only other two asyncio redis packages' maintainers as we've all gone dormant.

Again, I'm not sure how to fix this. I'm sure a PR'll be  appreciated if you can think of a way to accommodate for the linux package release cycle.

> head maintainer

You can find head maintainers of organizations by taking a look at the GitHub releases section or the commit history (I'm not really acquainted with apt package release cycles, so not sure how to translate it).

**Comment by ddevault** [comment]
bump.
