### ISSUE TITLE
Getting ReadOnly error when writing data to AWS elastic cache while the cluster is vertically scaled

### ISSUE THREAD

**Issue by Akshit8** [redis/redis-py#1764]
I have a python application that writes some data to AWS elastic cache cluster at a regular interval.

Here's an example script that simulates the functionality of my application. It also replicates the error that I have been facing.

```py
from datetime import datetime
import redis
import time
import sys
import random

class Config:
    default_host = "localhost"
    master_host = "xxx.xx.0001.xxxx.cache.amazonaws.com"
    replica_host = "xxx.xx.0001.xxxx.cache.amazonaws.com"
    redis_db = 8
    socket_conn_timeout = 10
    request_delay_sec = 0.1

def get_redis_client():
    return redis.Redis(
        host=Config.master_host,
        db=Config.redis_db,
        socket_connect_timeout=Config.socket_conn_timeout,
    )

def get_random_key_value():
    val = time.time()
    key = "test_key_" + str(random.randint(0, 100))
    return key, val

r = get_redis_client()

r.flushdb()

flag = False

while True:
    try:
        if flag:
            print("beat:", time.time())
        r.set(*get_random_key_value())
        time.sleep(Config.request_delay_sec)
    except redis.RedisError as re:
        print(datetime.now(), "Error:", type(re), re)
        flag = True
        # sys.exit()
    except KeyboardInterrupt:
        print("Stopping loop execution")
        sys.exit()
```

Here are the environment details of my application

 - OS(Ubuntu 18.04)
 - Python(v 3.7.0)
 - Redis-py(v 3.5.3)
 - AWS elastic cache(cluster mode disabled, 1 master node, 1 read replica)

When I scale my AWS elastic cache cluster vertically and the above script is running, I get the following error for few seconds while the cluster scaling-up is in process and then it goes away.

```bash
<class 'redis.exceptions.ReadOnlyError'> You can't write against a read only replica.
```

AWS docs also states that during vertical scaling process some inconsistencies may occur because of data syncing(https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/redis-cluster-vertical-scaling.html)

why this error occurs during the scale up process? how can it be fixed?

I tried the same thing with a golang script and it works perfectly fine.

**Comment by chayim** [comment]
@Akshit8 This looks like an issue in ElastiCache as opposed to redis-py. Would you mind having a look at redis-py 4? This a release back - and to be honest, I'd expect the same behaviour.

If you're feeling particularly testworthy I'd *love* a hand testing the cluster code we pulled in from @barshaul in redis-py 4.1.0rc1.

**Comment by Akshit8** [comment]
I'll try with redis-py 4.

The above version of the script in Golang works fine, could it be related DNS resolution?

**Comment by chayim** [comment]
I don't think so. Ultimately it's (Redis) ElastiCache returning that error.  That phrase doesn't appear anywhere in the codebase, so we're surfacing the alert you receive.

**Comment by barshaul** [comment]
Hey @Akshit8, I will try to reproduce it this week
Could you share the golang script you're using too?

**Comment by Akshit8** [comment]
@barshaul

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/go-redis/redis/v8"
)

const (
	DEFAULT_HOST              = "localhost"
	MASTER_HOST               = "xxx.ng.0001.xxx.cache.amazonaws.com"
	REPLICA_HOST              = "xxx.xx.ng.0001.xxx.cache.amazonaws.com"
	REDIS_DB_KEY              = 8
	SOCKET_CONNECTION_TIMEOUT = 5
	REQUEST_DELAY_SEC         = 100
)

func getRedisClient() *redis.Client {
	return redis.NewClient(&redis.Options{
		Addr:        fmt.Sprintf("%s:%d", DEFAULT_HOST, 6379),
		DB:          REDIS_DB_KEY,
		DialTimeout: time.Duration(SOCKET_CONNECTION_TIMEOUT * time.Second),
	})
}

func getRandomKeyValue() (string, string) {
	key := fmt.Sprintf("TEST_KEY_%d", time.Now().Unix())
	value := "THIS IS A TEST MESSAGE"
	return key, value
}

func main() {
	log.Println("starting execution")
	ctx := context.Background()
	flag := false
	rc := getRedisClient()

	err := rc.FlushDB(ctx).Err()
	if err != nil {
		log.Println("ERROR:", err)
		os.Exit(1)
	}

	for {
		key, value := getRandomKeyValue()
		err := rc.Set(ctx, key, value, time.Hour).Err()
		if flag {
			fmt.Println("beat:", time.Now())
		}
		if err != nil {
			flag = true
			log.Println("ERROR:", err)
		}

		time.Sleep(time.Duration(REQUEST_DELAY_SEC * time.Millisecond))
	}
}
```

**Comment by barshaul** [comment]
Hey,
 sorry for taking a long time - I was out sick all week >_<
I have been able to reproduce the issue with elasticache scale operation and redis-py and found the root cause.
When a Redis instance is created with redis-py, it opens a connection to the server, which remains open until some connection error or response error has occurred, and then it is disconnected and re-established. The DNS of the connection is resolved only when it is created (see socket.getaddrinfo in Connection/create_connection()). 
When you scale your elasticache cluster and the new node is ready, the DNS will be changed to point to the new node (and at this point, the old node will still be recognized as the replica of the new node).As a result, if you have an open connection to the old node, the DNS address will not be resolved again and the connection will stay hanging with the old node and you will encounter a 'readonly' error. Redis-py closes the connection after throwing an error, so the next time you run 'set', it will establish a new connection and the DNS will be resolved properly.

One solution is to catch the error and try again (as you did in the code above, however, you forgot to set the flag=true after the set() is successful).
A better solution would be to have the client do it - enable a retry mechanism on ReadOnly errors in Redis so that the client closes the old connection and tries again by opening a new one. 
Redis-py 4.0.0 added a retry mechanism, but it currently only supports retries when TimeoutErrors are encountered. 
I will create a PR to allow specific error types to be passed to enable the retry mechanism.
@chayim , what do you think about the suggested PR?

**Comment by Akshit8** [comment]
Makes sense @barshaul , thanks for the explanations!
