### ISSUE TITLE
RedisCluster doesn't support MULTI/EXEC and WATCH commands

### ISSUE THREAD

**Issue by barshaul** [redis/redis-py#1775]
**Version**: 4.1.0

**Description**: 
RedisCluster doesn't currently support MULTI/EXEC commands, and consciously WATCH isn't supported either.
It is challenging to enable MULTI/EXEC with WATCH in cluster mode - if we split the commands inside the multi/exec to different nodes, and then one of the keys in the request is changed under 'watch' - some of the commands will succeed and some won't, and it has an overall unexpected behavior.

With the current implementation, in case a user wants to use MULTI/EXEC on a specific node and knows what he's doing (all keys belong to the same slot, etc), he can get the Redis instance for that node and use Redis's API.

Adding this issue for future tracking and implementation.

**Comment by Grokzen** [comment]
MULTI/EXEC is a complex issue to solve as you have to decide what solution you want to implement as all of them has pros and cons in many and strange ways and when i attempted to implement it in the redis-py-cluster lib we always had issues with choosing what failure and rollback mode you want.

So in the general case you do not know or care about what node each key is sent to and each batch of commands and if you get into a case where one out of 5 nodes fail for some reason and it do not commit their keys, the other 4 nodes will commit their keys and you will get strange returns back to the user as compared to a single node, they expect the entire multi/exec to fail if it fails with one key so that it rolls back the entire stack you sent in. But in the cluster case you can get 4/5 commited and one failed and that created a headache for the user in how to handle and that there is no real ability to rollback already committed keys after you have run the EXEC. The only way i really see that you can make a copy of a single node redis behaviour is to implement a 3 way handshake solution to commit data where each node needs to report back to the client that "i am ready to commit this now" and then when all nodes you want to execute on it triggered by the client if all nodes report ok. This would cause many more issues where pinging back and forth and possibly blocking stuff will cause more issues then any performance gain.

Another solution is to fail the multi exec stack from the client side if all commands is not targeting a single node. This will cause the general case to fail as if you do not plan your keys and commands then you will not be able to use it there. In the specialized case where you plan and force hashslot for each key then you can support this. You get half of the feature but with more input and change in code for the user that you do not want to force upon them, but to support the feature it might be a good balance.

Another major issue when you split up a chain of commands that you order up from the client in a specific order you want to execute, A, B, C, D, E and you expect the keys to be executed in that order for some reason, when we batch them to different nodes you remove that kind of guarantee as maybe A + C goes to node 1 and B to node 2 and D + E to node 3 and things might be committed out of order. i guess in most cases this is not an issue directly but this might be more a theoretical issue that very few really hit.

I do think that Redis should solve this inside the server itself and to give a reference implementation on how to solve these complex features in a clustered environment because if this is only up to each client to implement whatever they like, they probably will implement completely different solutions that uses different methods and support different sets and use-cases in completely different ways.
