### ISSUE TITLE
Lock method does not exist in the redis client using cluster mode

### ISSUE THREAD

**Issue by jdavidagudelo** [redis/redis-py#1898]
**Version**: 4.1.1

**Platform**: Python 3.10.1 Ubuntu/21.10

**Description**: I am currently using the library https://github.com/Grokzen/redis-py-cluster to access my redis-cluster, I tried to move the code to the latest version of this library in cluster mode, but I found this library does not have a **lock** method when the client is used in cluster mode. Is there any workaround for this, will this library allow locks when using it in cluster mode or are locks not intended to work in cluster mode?

**Comment by jakebarnwell** [comment]
`redis-py-cluster` works fine with locks (noting that redis-py-cluster has its `RedisCluster` class extend redis-py's `Redis` class), so imagine this is mostly an issue of "we just haven't added support yet"?

After some poking, it looks like implementing `RedisCluster.lock()` properly involves doing something like the following:
1. add scripting support (`ScriptCommands`) to `RedisCluster` - needed for lua lock since it uses evalsha etc
2. either add a `.connection_pool.get_encoder()` stub to `RedisCluster` or change `Script` and `Lock` so they can get access to the encoder somehow via `RedisCluster.get_encoder()`... bbecause we have `Redis.connection_pool.get_encoder()` and `RedisCluster.get_encoder(), but there's no such thing as `RedisCluster.connection_pool`

Does this sound right @dvora-h ? Lock support is something I'm interested in as well.

**Comment by jakebarnwell** [comment]
TBH I'm not sure if this is something that someone else is tackling at the moment, but I'm happy to try

**Comment by chayim** [comment]
Correct. We haven't gotten there yet. @jakebarnwell if you'd like to - that would be fantastic!

I've assigned this to you simply because you volunteered. Please feel free to say no, of course :smiley:

**Comment by jakebarnwell** [comment]
Thank you! I've made this PR: https://github.com/redis/redis-py/pull/1937

I'm not sure how to assign somebody to it, but it's there...!

**Comment by jakebarnwell** [comment]
Sorry for the confusion -- #1937 adds scripting support, but does not yet implement the `.lock()` method. https://github.com/redis/redis-py/pull/2013 adds the anticipated `.lock()` method.
