### ISSUE TITLE
Version compatibility between redis-py and redis-server?

### ISSUE THREAD

**Issue by J-M0** [redis/redis-py#1925]
Hello,

 Is there anywhere that documents which versions of redis-py are compatible with which versions of redis-server? I can't seem to find any documentation about this.

Thank you.

**Comment by chayim** [comment]
@J-M0 actually you should be fine with 4.1.2 as well! There will be several functions that aren't available to you - due to running redis 5.0.5, but the library won't stop you from trying to call them!

**Comment by chayim** [comment]
@sav-norem Wanna?

**Comment by dmitriy-drenkalyuk** [comment]
Can we upgrade `redis-server` to `7.x` if we use `redis==4.4.0`?

**Comment by dvora-h** [comment]
@dmitriy-drenkalyuk Yes, you can. redis-py 4.4.0 has almost fully support for redis 7.x (supports everything except sharded-pubsub)

**Comment by logoff** [comment]
It would be very helpful for the community having a compatibility matrix to know which library version matches which server versions.

As an example, we are in an upgrade process of an old codebase, and we are not sure about the compatibility and the required effort to perform the upgrade.

**Comment by tstocker-black-cape** [comment]
@chayim Can you confirm that redis-py is backwards compatible with older server versions? We're using a Redis 3.2.2 server and we'd like to know if redis-py v4.4.0 will work?

+1 on adding a compatibility matrix to the documentation. Thanks!

**Comment by chayim** [comment]
Folks - the [supported matrix](https://github.com/redis/redis-py#supported-redis-versions) is on the main page. It may work with an old redis.. but there have been so many command, security, and ecosystem changes - I highly suggest upgrading.

**Comment by eliadl** [comment]
> Folks - the [supported matrix](https://github.com/redis/redis-py#supported-redis-versions) is on the main page. It may work with an old redis.. but there have been so many command, security, and ecosystem changes - I highly suggest upgrading.

Thanks for the compatibility matrix, but it's a bit unclear to me:

| Library version | Supported redis versions |
|-----------------|-------------------|
| 3.5.3 | <= 6.2 Family of releases |
| >= 4.5.0 | Version 5.0 to 7.0 |
| >= 5.0.0 | Version 5.0 to current |

because what I actually see in the first column is:

| Library version | 
|-----------------|
| redis == 3.5.3 | 
| redis >= 4.5.0, < 5.0.0 | 
| redis >= 5.0.0 | 

then it seems the matrix is missing two more ranges:
- redis < 3.5.3 
- redis < 4.5.0, >= 4.0.0

What about these?

**Comment by ns-jsu** [comment]
Hi
I have further question that we have been informed the [CVE-2021-31294](https://nvd.nist.gov/vuln/detail/CVE-2021-31294) vulnerability in redis/redis and it mentioned this issue has been fixed in 6.2.*
But we want to know which redis-py version have applied the 6.2.* redis/redis to make sure our code will not encounter the security concerns.

ps. currently our redis-py is 5.3.0

**Comment by petyaslavova** [comment]
Hi @ns-jsu, the compatibility information is available in the [README.md](https://github.com/redis/redis-py/blob/master/README.md#supported-redis-versions)

**Comment by ns-jsu** [comment]
@petyaslavova what I wanted to know is which redis version redis-py 6.2.* will use bcz it looks the matrix only mentioned the roughly range.

**Comment by petyaslavova** [comment]
Hi @ns-jsu, to clarify: redis-py is a client library, which means it doesn't include or manage the Redis server itself. Instead, it connects to an already running Redis server instance — whether that’s a local deployment, a container, or a managed service.

So when you're using redis-py 6.2.*, the version of the Redis server you connect to depends entirely on what you've deployed separately. 
The client supports compatibility with a range of server versions (as shown in the test matrix), but it doesn’t determine or install the server version itself.

We have a script that deploys a test setup used for our integration tests(runs the server as local containers), and it is typically configured to utilize the latest stable release.
