### ISSUE TITLE
Add support for COMMAND LIST

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1948]

**Comment by dogukanteber** [comment]
Hello @chayim. I would like to work on this issue. However, I have a question. How can I test this command? Since it returns all the commands I thought maybe I can get the number of commands and compare them. For instance, currently, I get 363 different commands. Assume I do this operation  ```len("command list") == 363``` and in the next version there is another command added. I could not think of a way to test this. Can you give me any advice?

**Comment by chayim** [comment]
@dogukanteber I think the right answer is to check that we receive a number of commands that's positive and high - as opposed to a specific number. The reason: redis will constantly change, but we'll keep trying to support as many versions as possible!

Ultimately we're trying to test each collection of possibilities. I think this means you need one function that that makes repeated calls and uses _r_ (the stock connection) and another that uses the _redismod_ client. Does that make sense?

Here's the direct link to the [new command](https://redis.io/commands/command-list).
CC: @dvora-h for visibility.
