### ISSUE TITLE
4.2.0 introduces breaking name changes

### ISSUE THREAD

**Issue by bobh66** [redis/redis-py#2061]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?

4.2.0

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

Linux

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

E   AttributeError: type object 'Path' has no attribute 'rootPath'

Updating to 4.2.0 breaks access to the items that were renamed by the fix for https://github.com/redis/redis-py/issues/1864

This was a breaking change that needed to have documentation in the release notes and preferably a major release update.

I'm not sure what can be done about it now other than updating the 4.2.0 release notes to document the change.

**Comment by tiptenbrink** [comment]
Ran into this issue as well.

**Comment by papakipos** [comment]
I also ran into this issue. This broke a lot of code. It should have been communicated better.

**Comment by dssecret** [comment]
Additionally, these changes are not reflected in the documentation for the examples of using the client for ReJSON found [here](https://github.com/redis/redis-py/blob/master/docs/examples/search_json_examples.ipynb).

**Comment by Andrew-Chen-Wang** [comment]
Apologies. I must've glossed over the the public methods on the initial grep somehow. I agree that there's nothing we can really do except update the release notes and changelog. If a suggestion popped up for adding compatibility by doing something like `rootPath = Path`, I would disagree upon adding it just to reduce clutter (not that redis-py isn't already cluttered). I'm not sure when 5.0.0 would be released; I would hope soon since at some point Python 3.6 needs to be dropped to improve the asyncio module.

**Comment by chayim** [comment]
IMHO redis-py 5 should be released **with various breaking changes**. I'd like to start planning that after we start profiling, and looking at reasonable improvement.

I am so sorry that we broke things. I admit to being embarrassed - we try to never break anything - at least if it's not a major - or intentional.

Plan of action we can agree on:
1. Update the JSON example @dssecret has pointed out 
2. Back-update the release notes for 4.2.0

Is there anything else that would be particularly useful? I'd like to make sure we do right by the community.

**Comment by akx** [comment]
@chayim Now that you mention it, perhaps 5.0.0 should split the nonfree modules out, á la the discussion in https://github.com/redis/redis-py/issues/1715?
