### ISSUE TITLE
invalid url silently causes connection to localhost

### ISSUE THREAD

**Issue by kristjanvalur** [redis/redis-py#2098]
**Version**: 4.2.2

**Platform**: python 3.10 on windows

**Description**: 
incorrectly formed url, for example `"redis:foo.bar.com:1234"` passed to `redis.asyncio.Redis.from_url()`
silently causes a connection to `"localhost:6379"` instead.

**Expected behaviour**:
a `ValueError` or similar should be raised.

**Comment by kamyabzad** [comment]
This is somehow related to `urllib.parse.urlparse`. `urlparse` doesn't consider `redis:foo.bar.com:1234` as an "incorrectly fomred url", but rather an alternative form of `redis:///foo.bar.com:1234`, meaning no hostname, no port, only a `/foo.bar.com:1234` "path". Although, I agree that it should raise an error, since url paths are used for specifying Redis DB number. I will open a pull request to fix this.

**Comment by kamyabzad** [comment]
Check out [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt). `redis:foo.bar.com:1234` is not an incorrectly formed url, it's actually equivalent to `redis:///foo.bar.com:1234`, an as far as Redis defaults are concerned, equivalent to `redis://localhost:6379/foo.bar.com:1234`. `foo.bar.com:1234` is interpreted as a `path`, used for extracting Redis db number if possible and if not, it's just ignored. You could use `redis.asyncio.Redis.from_url("redis:1")` (or `redis.Redis.from_url("redis:1")`) to access db 1 on localhost:6379.

**Comment by kristjanvalur** [comment]
Yes,  you are right.  just confirmed with urllib.parse.urlparse().  Although I guess one might want to emit a warning if the "path" component makes no sense.
Sorry for the noise.
