### ISSUE TITLE
async redis perfomance

### ISSUE THREAD

**Issue by arebrik** [redis/redis-py#2228]
**Version**: 
redis-py 4.3.3
redis 7.0.2

**Platform**: 
Python 3.10 / Mac ARM

**Description**: 
According to [this](https://github.com/aio-libs/aioredis-py/issues/1208)  issue, aioredis lib has significant performance degradation after 2 version. As I understand, aioredis was merged into redis-py lib with this problem(it can be reproduce with same code except import redis-py) . 

Can you please tell if there any play to fix it in redis-py lib?

**Comment by wannabe-quant** [comment]
bringing this back up... any idea if this will be resolved?

**Comment by sgjurano** [comment]
Migration from aioredis to redis-py significantly reduces performance due to some changes between aioredis 1.3.1 and 2.0.1, noted in issue https://github.com/aio-libs/aioredis-py/issues/1208, current versions of redis-py are unusable for high load environments (>30k rps get/set commands).

It will be great if you can fix it.
