### ISSUE TITLE
Using redis-py to access a redis-cluster  is so slowly

### ISSUE THREAD

**Issue by hert525** [redis/redis-py#2371]
Using redis-py to access a redis-cluster set with a key of more than 100m takes 6s, which is too slow. How can I optimize it, but when I use the same environment to access a standalone, it is very fast

**Comment by utkarshgupta137** [comment]
This is because the key needs to be hashed before being sent to the correct node. It would be helped a little by #2118, but the amount of time would still be directly proportional to the length of the key. You could try using hashtags in your keys (keep it near the start): https://redis.io/docs/reference/cluster-spec/#hash-tags

**Comment by hert525** [comment]
![Uploading image.png…]()
tks

**Comment by hert525** [comment]
> Can you share a sample code to illustrate the performance difference?

![image](https://user-images.githubusercontent.com/19421393/190135172-527c83c0-2dee-498c-a7b9-629ece0342c0.png)
tks

**Comment by hert525** [comment]
![image](https://user-images.githubusercontent.com/19421393/190296720-23251b7c-0d0d-4179-8112-833d6c7bc884.png)
tks

**Comment by hert525** [comment]
> Can you share a sample code to illustrate the performance difference?

hi
