### ISSUE TITLE
Need info on using redis-py connectionPool with Gunicorn workers

### ISSUE THREAD

**Issue by pjain05** [redis/redis-py#2400]
I want to understand how redis-py connection pool works with Gunicorn server. As we know, Gunicorn arbiter forks the workers so, will it mean each Gunicorn worker has its own Connection Pool?

If yes, is there a way to have a common connection pool for all the Gunicorn workers. 

My project setup is like this: -

We have a flask app which is running in GKE(Google Kubernetes Cluster) 
This app has 40 pods 
and each pod has 6 Gunicorn workers
and connection Pool has maximum client limit as 1000

So, in the worst case, total no of active connection from client side could be 1000x40x6?

redis-py version: 3.5.3

**Comment by akx** [comment]
> each Gunicorn worker has its own Connection Pool?

Regardless of application server, each process it spawns will have its own connection pool because you can't easily share the sockets (especially SSL sockets!) between processes.

> If yes, is there a way to have a common connection pool for all the Gunicorn workers.

Not without additional legwork (e.g. another single process that acts as a proxy for your workers to talk to Redis, and maintains a single connection pool).

> total no of active connection from client side could be 1000x40x6?

Sounds about right to me...

**Comment by pjain05** [comment]
Thanks man @akx
