### ISSUE TITLE
redis pipline executed multiple, and the time consumption gradually increases.

### ISSUE THREAD

**Issue by SmileTM** [redis/redis-py#2448]
The pipe is executed multiple times, and the time consumption gradually increases. How to solve this problem?

```python
redisClient = redis.RedisCluster(host=host, port=port, password=password,decode_responses=True)
pipe = redisClient.pipeline()
for step in range(10):
    for i in range(10000000):
        pipe.delete(f"key-{i}")
    start = time.time()
    res = pipe.execute()
    end = time.time()
    print(f"cost time: {end-start}")
```

**Comment by chayim** [comment]
@SmileTM I see that you've created a pipeline outside of a loop.. but then you execute the pipeline within the outer loop. What happens if you create the pipeline within the inner loop?

Also, if you could kindly highlight - what version of redis-py are you using?

Also, WDYT about trying async given your use csae?

**Comment by SmileTM** [comment]
> @SmileTM I see that you've created a pipeline outside of a loop.. but then you execute the pipeline within the outer loop. What happens if you create the pipeline within the inner loop?
> 
> Also, if you could kindly highlight - what version of redis-py are you using?
> 
> Also, WDYT about trying async given your use case?

the redis  version: 4.3.4 
yes, you are right.   create the pipeline within the inner loop solved this problem.  Does this mean creating a new pipeline for each execution?
