### ISSUE TITLE
Async RedisCluster missing pubsub() support

### ISSUE THREAD

**Issue by itsBrady** [redis/redis-py#2497]
**Version**: 4.4.0

**Platform**: python 3.8, 

**Description**: async RedisCluster class does not have pubsub() function, or any pubsub commands.

Looking to move from aioredis to this library for cluster mode support. Making a simple test case I get this error:
```
Traceback (most recent call last):
|   File "src/test.py", line 26, in <module>
|     loop.run_until_complete(main())
|   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
|     return future.result()
|   File "src/test.py", line 21, in main
|     test = cluster.pubsub()
| AttributeError: 'RedisCluster' object has no attribute 'pubsub'
```
Looking in the documentation, I see that the sync client of RedisCluster has pubsub included but not the async RedisCluster. Is there a reason for this? Any workarounds that can be shared, or is the expectation to use `execute_command` to manually handle these commands?

**Example code**:
```
import asyncio
import redis.asyncio as redis

cluster = redis.RedisCluster(
    host="", password="", read_from_replicas=True
)

async def main():
    await cluster.initialize()
    test = cluster.pubsub()
    await cluster.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by itsBrady** [comment]
down to help add this functionality if someone has time to get me up to speed on the codebase a bit.

**Comment by itsBrady** [comment]
Current sticking point is that the ClusterPubSub class for the sync implementation seems to work with ConnectionPool instances, while the async RedisCluster definition each cluster node seems to manage their own list of free/available Connections. 

Curious if I should try to port the async stuff to more closely match the sync stuff, or copy and paste the pubsub stuff and change it to be okay with just Connections instead of ConnectionPools

**Comment by itsBrady** [comment]
@utkarshgupta137 if you have time to chat I'd love to help add this functionality

My current sticking point is that the ClusterPubSub class for the sync implementation seems to work with ConnectionPool instances, while the async RedisCluster definition each cluster node seems to manage their own list of free/available Connections. 

Curious if I should try to port the async stuff to more closely match the sync stuff, or copy and paste the pubsub stuff and change it to be okay with just Connections instead of ConnectionPools

**Comment by utkarshgupta137** [comment]
@itsBrady Sorry for replying late.

I had written the async impl with performance in mind. Hence I opted to manage connections directly instead of creating an async client & then getting a ConnectionPool from there. This led to some significant differences in sync & async internals (as well as standalone/cluster internals), but it led to about 10-15% improvement in performance AFAIR.
The use of a [deque](https://github.com/redis/redis-py/blob/a9ef0c5d0080bd14e2f189d7f31d83e758346a8d/redis/asyncio/cluster.py#L965) instead of a list for storing free connections & the lack of support of forking (removing [pid checks & required locks](https://github.com/redis/redis-py/blob/a9ef0c5d0080bd14e2f189d7f31d83e758346a8d/redis/asyncio/connection.py#L1386)) made a significant difference in performance.
Hence, I would not recommend simply using async ConnectionPools from the standalone client. Ideally, the same changes should be ported to the async ConnectionPool & then we could use the connection pool for the cluster client.

I've never used PubSub & I'm unfamiliar with the code, so I'm not sure why you need ConnectionPools specifically for using PubSub. You should probably look at the differences between standalone & cluster sync PubSub & then apply the same to the async PubSub, instead of porting the sync cluster to async. (i.e. do async standalone -> async cluster, not sync cluster -> async cluster). Also, the [coredis](https://coredis.readthedocs.io/en/stable/api.html#coredis.RedisCluster.pubsub) library already has support for PubSub for async cluster. I think it has a significantly different architecture to the redis-py library, but it may helpful.

I've switched jobs & no longer use Redis (or even Python), so I won't be able to bring feature parity to async cluster client as I hoped to do. But if you've any questions, feel free to ping or mention me.

**Comment by itsBrady** [comment]
@utkarshgupta137 No problem at all!

coredis seems like a good option, thank you for sharing I did not know it existed, I will continue to eval and let you know if I have any more questions. Thanks for your time friend!
