### ISSUE TITLE
Decode responses option outside connection pool not respected

### ISSUE THREAD

**Issue by ahmedabdou14** [redis/redis-py#3088]
## Problem
When creating a basic `ConnectionPool` with no extra options and then using this pool to instantiate a new `Redis` using that pool but with the extra `decode_responses=True` option, response results will not be decoded and the option will not be respected. However if we add the `decode_responses=True` option to the pool directly, all redis connections to that pool will decode responses as expected.

## Failing Example
```python
import redis.asyncio as aioredis

from app.core.config import settings

async_redis_pool = aioredis.ConnectionPool.from_url(settings.REDIS_URI)

class AsyncRedisClient(aioredis.Redis):
    def __init__(self):
        super().__init__(
            connection_pool=async_redis_pool,
            decode_responses=True,
        )

....

rc = AsyncRedisClient()
await rc.set("key", "value")
res = await rc.get("key")
type(res) # bytes
```

## Working Example
```python
import redis.asyncio as aioredis

from app.core.config import settings

async_redis_pool = aioredis.ConnectionPool.from_url(
    str(settings.REDIS_URI),
    decode_responses=True,
)

class AsyncRedisClient(aioredis.Redis):
    def __init__(self):
        super().__init__(connection_pool=async_redis_pool)

....

rc = AsyncRedisClient()
await rc.set("key", "value")
res = await rc.get("key")
type(res) # str
```

**Comment by dvora-h** [comment]
@ahmedabdou14 You can't mix between the option to use your pre-defined connection pool to the option that the client creates it. if you want to use decode_responses option you should pass it to your connection pool.

And yes, when you use connection pools all the connection in the pool gets the same configurations options so this is the expected behavior.

**Comment by pickfire** [comment]
I imagine this would be messy if we need to support couple methods since some libraries need the non-decoded version. Then we would have 4 connection pools if we want to use it:

- sync decoded pool
- sync non-decoded pool
- async decoded pool
- async non-decoded pool

I am not sure if that's a good idea, or we have to go about rewriting libraries.
