### ISSUE TITLE
5.0.9 missing in pypi

### ISSUE THREAD

**Issue by raphaelauv** [redis/redis-py#3344]
![image](https://github.com/user-attachments/assets/87ff8d17-d235-4c69-9842-8ab0058ceece)

version 5.0.9 is missing in pypi. Thanks all

**Comment by beruic** [comment]
Why is this not being addressed?

**Comment by willfrey** [comment]
https://github.com/redis/redis-py/blob/e82c56eb9a18ea3e7e1ab46825f79282abc93ebc/setup.py#L11

Looks like the version metadata in the setup.py file for the 5.0.9 release was never actually changed from 5.0.8 to 5.0.9. Maybe that's why?

The source distributions in the 5.0.9 release also have this same problem.

Just taking a guess!
